### ISSUE TITLE
Error while using Automagic plugin in EEGLAB

### ISSUE THREAD

**Issue by kns37** [methlabUZH/automagic#13]
Hi Automagic team,

Thank you so much for making this toolbox available. I have run some test files through the preprocessing steps and am interested in viewing the files using the plugin within EEGLAB. However, when I follow the steps described for importing the results from a project I run into an error. When I click on the Automagic extension and then select Import Automagic Results, here is the error I receive:

![image](https://user-images.githubusercontent.com/55501012/65163454-910e4f00-da00-11e9-9474-bfd4b77025e8.png)

I am using Matlab Version R2019a, EEGLAB v14.0.0 and Automagic v2.3.8. 

Would appreciate your guidance navigating this issue.

Thank you!

**Comment by nickilanger** [comment]
Hi, 

Can you tell me the reason, why you want to use the EEGLab plugin. Because, you can simple look at the data by loading the output of Automagic in MATLAB and then you have it as EEGlab structure. Do you want to use the EEGLab GUI (that's kind of the only reason, why you would want to use the Automagic EEGlab plugin). 

You would need to provide more details about the import? Are you trying to import one data set? Do you see the results in the GUI?

Best, 

Nicolas
