### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by Mode5t** [methlabUZH/automagic#8]
Hi methlabUZH!
         I'm Chen,parallel computing started working.but I have 32 subjects,and some of subjects didn't pass the preprocessed stage,and throw index out of bounds exception,like this.

![error](https://user-images.githubusercontent.com/32796991/63311597-2bf80880-c331-11e9-94f5-23965fbf7fa3.png)
         ERROR
![EEG](https://user-images.githubusercontent.com/32796991/63311596-2bf80880-c331-11e9-98a3-d43fd6953c5e.png)
        EEG structure
        All data have 32 channels,but 
        "noChannelAsCell{nochanId}=EEG.chanlocs(g.nochannel(nochanId)).labels;"
        Exception tell me EEG.chanlocs size is 30,and different subject throw same exception,also 30 index out of bounds.

I am looking forward to your reply.
Thank you
Chen

**Comment by Mode5t** [comment]
![EEG](https://user-images.githubusercontent.com/32796991/63311550-f9e6a680-c330-11e9-8e58-683dec6788cf.png)
![error](https://user-images.githubusercontent.com/32796991/63311551-f9e6a680-c330-11e9-962d-bd07b1f74613.png)

**Comment by Mode5t** [comment]
Hi methlabUZH!
I found that option 'has aleardy a reference chanel' will cause index out of bounds exception in interpolation stage, when this option was chose,exception happened,if choose add a new channel,it work.some screenshot as follow:
![project](https://user-images.githubusercontent.com/32796991/63395708-2fee5e00-c3f7-11e9-9eae-29ff1fc9866e.png)
project page
![configuration](https://user-images.githubusercontent.com/32796991/63395714-34b31200-c3f7-11e9-93d5-ccdca1c401e6.png)
configuration page
![插值报错](https://user-images.githubusercontent.com/32796991/63395719-38469900-c3f7-11e9-84e7-6005e23b8c39.png)
exception
![image](https://user-images.githubusercontent.com/32796991/63395984-231e3a00-c3f8-11e9-9047-b0e67850caa9.png)
work without providing reference channel

Finally,when I provide a reference channel index,and the output data structure will remove one channel data,I think this channel should be this reference channel,but when I open it found that the index channel with all 0,I think maybe some var error during the processing.Maybe automagic remain has some bug,but it' also a great work. 

I am looking forward to your reply.
Thank you
Chen

**Comment by nickilanger** [comment]
Hi Chen, 

Thanks for your messages. 

First of all we need to know, whether your data actually does contain the reference electrode or not. Do all data you want to preprocess have the reference channel and the same index. If not, you need to create seperate projects. 

If all files have a reference channel in the data (you can check them by importing it into EEGlab and see if any of of the rows in EEG.data are zero), you did the right thing to select that "has already reference channel" and then add the index. As you correctly identified that the after preprocessing the index of this channel is set to zero. The reference is always zero and should have zeros already before the preprocessing (otherwise this electrode is not the reference channel and you the data actually does not contain the reference channel?). To sum up, the preprocessed data are referenced to the original reference electrode. Thus the reference channel has to be zero. You can re-reference it to average reference or any other reference later (e.g. in EEGLAB). 

Hope this makes sense. 

Best, 

Nicolas
